name: Test Action

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test-broker:
    name: Test EMQ X Docker image version [${{ matrix.version }}]
   
    runs-on: ubuntu-latest

    strategy:
      matrix:
        version: ['4.2.5', 'latest']

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Start EMQ X
        uses: ./
        with:
          version: ${{ matrix.version }}
